version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enigma_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/enigma_db
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_STORE_PATH: /data/telegram_channels.json
      TELEGRAM_TICKET_STORE_PATH: /data/telegram_tickets.json

    volumes:
      - ./data:/data

  bot:
    build: ./backend
    command: ["python", "-m", "app.bot.bot_service"]
    depends_on:
      - backend
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_STORE_PATH: /data/telegram_channels.json
      TELEGRAM_TICKET_STORE_PATH: /data/telegram_tickets.json
    volumes:
      - ./data:/data

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
