"""
Seed the database with demo tickets on first startup.
Called from main.py via the startup event — runs only if the tickets table is empty.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import select, func

from app.core.db import SessionLocal
from app.core.models import Ticket

SEED_TICKETS = [
    {
        "created_at": datetime(2026, 1, 3, 8, 15),
        "full_name": "Захаров Виктор Павлович",
        "facility": "ООО «СибГазСервис»",
        "phone": "+7 (383) 111-22-33",
        "email": "v.zaharov@sibgasserv.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Дисплей не отображает показания после обслуживания",
        "original_text": "После очередного планового обслуживания газоанализатор ДГС-230 перестал отображать показания на дисплее. Индикатор питания горит зелёным, связь по RS-485 присутствует, но дисплей — полностью чёрный. Прошу предоставить инструкцию по перепрошивке дисплейного модуля.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 1, 5, 9, 30),
        "full_name": "Орлова Наталья Дмитриевна",
        "facility": "АО «УральХимМаш»",
        "phone": "+7 (343) 555-66-77",
        "email": "n.orlova@uralchimmash.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "software",
        "issue_summary": "Запрос пароля DGS BLE Android. ID: f12aa3c7e501",
        "original_text": "Запрос пароля доступа к приложению DGS BLE Android для нового устройства. Прибор приобрели в декабре 2025 г. ID устройства: f12aa3c7e501. Орлова Наталья Дмитриевна, Инженер КИПиА, АО «УральХимМаш».",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 1, 7, 10, 0),
        "full_name": "Терентьев Борис Геннадьевич",
        "facility": "ЗАО «НефтеПромСнаб»",
        "phone": "+7 (347) 222-44-66",
        "email": "b.terentiev@neftepromsn.ru",
        "device_numbers": "ДГС-230/CH4",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "документация",
        "issue_summary": "Запрос паспорта и сертификата поверки (зав. № 2411-08731)",
        "original_text": "Прошу выслать актуальный паспорт и сертификат о поверке для газоанализатора ДГС-230/CH4 (зав. № 2411-08731). Документы необходимы для прохождения планового аудита промышленной безопасности в феврале 2026 года.",
        "ai_response": None,
        "status": "Закрыто",
    },
    {
        "created_at": datetime(2026, 1, 9, 11, 45),
        "full_name": "Белова Ирина Константиновна",
        "facility": "ООО «ЭнергоМонтаж»",
        "phone": "+7 (495) 777-12-34",
        "email": "i.belova@energomontag.ru",
        "device_numbers": "ДГС ЭРИС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "software",
        "issue_summary": "Нет связи с контроллером ABB AC500 по Modbus TCP",
        "original_text": "При монтаже ДГС ЭРИС-230 в щит управления обнаружили, что прибор не распознаётся контроллером ABB AC500 по протоколу Modbus TCP. Настройки IP, маски и порта выставлены согласно руководству. Просьба предоставить пример регистровой карты Modbus TCP.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 1, 12, 8, 0),
        "full_name": "Кузнецов Алексей Романович",
        "facility": "ПАО «СевГаз»",
        "phone": "+7 (8162) 333-55-77",
        "email": "a.kuznetsov@sevgaz.ru",
        "device_numbers": "ДГС-230/H2S",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "коммерческий запрос",
        "issue_summary": "Запрос модификации с диапазоном H2S 0–500 ppm, 20 единиц",
        "original_text": "Нас интересует возможность поставки газоанализаторов с расширенным диапазоном измерения H2S: не 0–50 ppm, а 0–500 ppm. Применение — контроль атмосферы в канализационных коллекторах. Уточните наличие и сроки поставки на 20 единиц.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 1, 14, 14, 20),
        "full_name": "Степанова Ольга Ивановна",
        "facility": "ООО «ГазНадзорСервис»",
        "phone": "+7 (831) 444-88-11",
        "email": "o.stepanova@gaznadzor.ru",
        "device_numbers": "ДГС-230/CO",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Отрицательные показания при -20°С",
        "original_text": "Датчик ДГС-230/CO при температуре ниже -20°С начинает показывать отрицательные значения (до -12 ppm). Эксплуатация ведётся на открытой площадке в условиях западносибирского климата. Является ли это нормальным дрейфом нуля или признаком неисправности?",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 1, 16, 9, 10),
        "full_name": "Громов Сергей Юрьевич",
        "facility": "ЗАО «ПромТехГаз»",
        "phone": "+7 (812) 999-00-11",
        "email": "s.gromov@promtechgas.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "software",
        "issue_summary": "Совместимость с SCADA WinCC v7.5 через OPC-сервер",
        "original_text": "Прошу подтвердить совместимость газоанализатора с программным обеспечением SCADA WinCC v7.5. Нам требуется интеграция через OPC-сервер. Ранее использовали оборудование другого производителя, документация по ЭРИС в части OPC не найдена.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 1, 19, 15, 30),
        "full_name": "Поляков Николай Фёдорович",
        "facility": "ООО «АвтоматикаПлюс»",
        "phone": "+7 (351) 222-11-99",
        "email": "n.polyakov@avtomatika-plus.ru",
        "device_numbers": "ДГС-230/IR-CH4",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Занижение показания при калибровке: 37% НКПР вместо 50%",
        "original_text": "В ходе калибровки ДГС-230/IR-CH4 по поверочному газу ПНГ/N2 (50% НКПР) прибор выдаёт показание 37% НКПР вместо ожидаемых 50%. Просьба проконсультировать по корректировке коэффициента чувствительности.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 1, 21, 10, 5),
        "full_name": "Дмитриева Екатерина Олеговна",
        "facility": "АО «РефтПром»",
        "phone": "+7 (343) 888-77-66",
        "email": "e.dmitrieva@reftprom.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "документация",
        "issue_summary": "Максимальная длина кабельной линии RS-485 (450 м)",
        "original_text": "Уточните максимальную длину кабельной линии от датчика до блока индикации при использовании кабеля КВВГнг сечением 0,75 мм². Проектируемый участок составляет 450 метров. Допустимо ли применение повторителей RS-485?",
        "ai_response": None,
        "status": "Закрыто",
    },
    {
        "created_at": datetime(2026, 1, 23, 13, 0),
        "full_name": "Лебедев Антон Владимирович",
        "facility": "ООО «МегаЭнерго»",
        "phone": "+7 (495) 234-56-78",
        "email": "a.lebedev@megaenergo.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Позитив",
        "category": "коммерческий запрос",
        "issue_summary": "Запрос выездного обучения персонала (4 человека)",
        "original_text": "Хотели бы заказать обучение для 4 новых сотрудников: монтаж, настройка, калибровка ДГС-230. Возможно ли выездное обучение на нашем предприятии в Московской области? Уточните стоимость и ближайшие доступные даты.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 1, 26, 7, 50),
        "full_name": "Зайцев Павел Дмитриевич",
        "facility": "ГУП «ЖилСервисТех»",
        "phone": "+7 (495) 001-23-45",
        "email": "p.zaitsev@jilservtech.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Прибор не запускается после скачка напряжения (3 красных мигания)",
        "original_text": "После скачка напряжения в сети один из датчиков ДГС-230 не запускается. При подаче питания светодиодный индикатор мигает красным трижды и прибор уходит в защитный режим. Прошу разъяснить значение кода ошибки и порядок восстановительных действий.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 1, 28, 16, 0),
        "full_name": "Карпова Светлана Алексеевна",
        "facility": "ООО «АрктикГаз»",
        "phone": "+7 (499) 345-67-89",
        "email": "s.karpova@arcticgas.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "коммерческий запрос",
        "issue_summary": "Запрос модификации с сертификатом DNV и классом IP68",
        "original_text": "Для проекта на арктическом шельфе нам необходимы газоанализаторы с сертификатом DNV для морских применений и классом защиты IP68. Есть ли такие модификации или возможность изготовить под заказ? Планируем закупку 15 единиц.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 1, 30, 9, 15),
        "full_name": "Никитин Роман Сергеевич",
        "facility": "АО «КировХим»",
        "phone": "+7 (8332) 456-78-90",
        "email": "r.nikitin@kirovhim.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Негатив",
        "category": "hardware",
        "issue_summary": "Повторяющийся сбой «Sensor Fault» через 20–30 мин, прибор на гарантии",
        "original_text": "Прибор ДГС-230 постоянно выдаёт аварийный сигнал «Sensor Fault» через 20–30 минут работы. После перезапуска работает нормально, затем ошибка повторяется. Прибор на гарантии (дата покупки — 15.09.2025). Прошу организовать гарантийный ремонт.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 1, 11, 30),
        "full_name": "Соловьёва Анна Михайловна",
        "facility": "ООО «ТопливоСервис»",
        "phone": "+7 (391) 567-89-01",
        "email": "a.solovieva@toplivoserv.ru",
        "device_numbers": "ГК-01 IR CH4",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "документация",
        "issue_summary": "Уточнение межповерочного интервала (паспорт vs метрологическая служба)",
        "original_text": "Уточните межповерочный интервал для газоанализатора ГК-01 IR CH4. В паспорте указан МПИ 1 год, однако наша метрологическая служба настаивает на 6 месяцах. Прошу предоставить официальное письмо с указанием МПИ.",
        "ai_response": None,
        "status": "Закрыто",
    },
    {
        "created_at": datetime(2026, 2, 3, 8, 45),
        "full_name": "Федотов Илья Олегович",
        "facility": "ЗАО «ИнтерГазСтрой»",
        "phone": "+7 (861) 678-90-12",
        "email": "i.fedotov@intergaz.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "software",
        "issue_summary": "Запрос пароля DGS BLE Android. ID: 3b7ef214cc92",
        "original_text": "Запрос пароля DGS BLE Android. Федотов Илья Олегович, Старший инженер КИПиА, ЗАО «ИнтерГазСтрой», +7 (861) 678-90-12. ID устройства: 3b7ef214cc92.",
        "ai_response": None,
        "status": "Закрыто",
    },
    {
        "created_at": datetime(2026, 2, 5, 10, 20),
        "full_name": "Тихомиров Геннадий Васильевич",
        "facility": "ПАО «ВолгаТрансГаз»",
        "phone": "+7 (8422) 789-01-23",
        "email": "g.tikhomirov@volgagaz.ru",
        "device_numbers": "ДГС-230/H2S",
        "device_type": "газоанализатор",
        "emotional_tone": "Негатив",
        "category": "hardware",
        "issue_summary": "Перекрёстная чувствительность к парам бензина",
        "original_text": "На нескольких датчиках ДГС-230/H2S наблюдается перекрёстная чувствительность к парам бензина. При прохождении погрузчиков вблизи датчиков показания растут до 15–18 ppm даже при отсутствии реального H2S. Прошу рекомендовать фильтрующий элемент.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 7, 14, 0),
        "full_name": "Самойлова Юлия Евгеньевна",
        "facility": "ООО «ГазСтройПроект»",
        "phone": "+7 (423) 890-12-34",
        "email": "y.samoilova@gasstroypro.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "документация",
        "issue_summary": "Расстояния между датчиками в помещении 600 м²",
        "original_text": "Для проектируемого объекта нам нужна документация по допустимым расстояниям между датчиками ДГС-230 при мониторинге утечки метана в закрытых помещениях площадью 600 м². Хотели бы получить рекомендации от производителя.",
        "ai_response": None,
        "status": "Закрыто",
    },
    {
        "created_at": datetime(2026, 2, 10, 9, 0),
        "full_name": "Кириллов Андрей Петрович",
        "facility": "АО «СамараТехноГаз»",
        "phone": "+7 (846) 901-23-45",
        "email": "a.kirillov@samtechgas.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Негатив",
        "category": "software",
        "issue_summary": "Три датчика из пяти периодически теряют связь по RS-485",
        "original_text": "В течение последних двух недель три датчика из пяти в одном шкафу управления периодически теряют связь по RS-485. Сеть терминирована, экран кабеля заземлён. Проблема возникает непредсказуемо, иногда несколько раз в день.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 12, 15, 10),
        "full_name": "Яковлева Марина Сергеевна",
        "facility": "ООО «БашкирНефтеХим»",
        "phone": "+7 (347) 012-34-56",
        "email": "m.yakovleva@bashkimhim.ru",
        "device_numbers": "ДГС-230/NH3",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "коммерческий запрос",
        "issue_summary": "Счёт на 10 единиц ДГС-230/NH3 Ex d + расширенная гарантия 3 года",
        "original_text": "Просим выставить счёт на 10 единиц ДГС-230/NH3 с диапазоном 0–100 ppm, исполнение взрывозащищённое 1ExdIIBT4. Необходима поставка до 01.04.2026. Также запросите стоимость расширенной гарантии на 3 года.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 2, 14, 10, 30),
        "full_name": "Денисов Константин Леонидович",
        "facility": "ГК «АвтоматПром»",
        "phone": "+7 (812) 123-45-67",
        "email": "k.denisov@avtomatprom.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Негатив",
        "category": "software",
        "issue_summary": "После обновления прошивки 3.2.1 нет ответа по RS-485",
        "original_text": "После обновления прошивки до версии 3.2.1 приборы ДГС-230 перестали отвечать на команды по RS-485. Откат на 3.1.4 решает проблему. Прошу предоставить список изменений (changelog) для версии 3.2.1.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 17, 8, 30),
        "full_name": "Рыбакова Татьяна Игоревна",
        "facility": "ООО «ТехЭнергоСервис»",
        "phone": "+7 (495) 234-00-11",
        "email": "t.rybakova@tesen.ru",
        "device_numbers": "ДГС-230/CO2",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "коммерческий запрос",
        "issue_summary": "Запрос 20 электрохимических ячеек ECC-230-CO2, возможна скидка",
        "original_text": "Уточните срок поставки запасных электрохимических ячеек для ДГС-230/CO2 (каталожный номер ECC-230-CO2). Нам необходимо 20 штук. Также спросите о возможности скидки при объёмной закупке.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 2, 19, 11, 0),
        "full_name": "Морозов Владислав Антонович",
        "facility": "ЗАО «СпецПромМонтаж»",
        "phone": "+7 (3452) 345-11-22",
        "email": "v.morozov@specprommontag.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Позитив",
        "category": "software",
        "issue_summary": "Совместимость с HART 7.x и запрос EDDL-файла для AMS Device Manager",
        "original_text": "Просим уточнить, совместим ли ДГС-230 с новой версией протокола HART 7.x, и если да, можно ли получить EDDL-файл для интеграции с AMS Device Manager? Документация на сайте содержит только описание HART 5.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 21, 9, 40),
        "full_name": "Суворова Елена Борисовна",
        "facility": "ООО «НефтеГазПроект»",
        "phone": "+7 (495) 456-22-33",
        "email": "e.suvorova@ngproject.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "документация",
        "issue_summary": "Погрешность +8% при горизонтальном монтаже датчиком вниз",
        "original_text": "При установке ДГС-230 в горизонтальном положении (датчиком вниз) наблюдается систематическая погрешность +8% относительно вертикального монтажа. Прошу разъяснить допустимые углы монтажа.",
        "ai_response": None,
        "status": "Закрыто",
    },
    {
        "created_at": datetime(2026, 2, 23, 14, 15),
        "full_name": "Антонов Максим Владимирович",
        "facility": "АО «СибирьАвтоматика»",
        "phone": "+7 (3832) 567-33-44",
        "email": "m.antonov@sibautomatica.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "software",
        "issue_summary": "Запрос пароля DGS BLE Android. ID: 9c3da512f780",
        "original_text": "Запрос пароля DGS BLE Android. Антонов Максим Владимирович, Инженер по автоматизации, АО «СибирьАвтоматика», +7 (3832) 567-33-44. ID устройства: 9c3da512f780.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 2, 24, 10, 0),
        "full_name": "Егорова Людмила Павловна",
        "facility": "ООО «КоксоХимГаз»",
        "phone": "+7 (3843) 678-44-55",
        "email": "l.egorova@koksohimgaz.ru",
        "device_numbers": "ДГС-230/CO",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Перекрёстная чувствительность к H2 при измерении CO в газовой смеси",
        "original_text": "На производстве используем смесь: CO 30%, H2 40%, CH4 15%, N2 остальное. Уточните, подходит ли электрохимическая ячейка ДГС-230/CO для работы в такой смеси, или требуется специальная компенсация по водороду?",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 25, 8, 0),
        "full_name": "Большаков Дмитрий Николаевич",
        "facility": "ПАО «КировЭнерго»",
        "phone": "+7 (8332) 789-55-66",
        "email": "d.bolshakov@kirovenergo.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Один прибор в режиме Fault при подключении 6 датчиков к одному блоку питания",
        "original_text": "При подключении нескольких датчиков ДГС-230 к одному блоку питания 24В/2А один из приборов постоянно уходит в режим «Fault». При отключении остальных датчиков проблемный прибор работает нормально. Прошу рекомендовать правильную схему питания для шести датчиков.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 25, 12, 30),
        "full_name": "Романова Виктория Андреевна",
        "facility": "ООО «РусХимПром»",
        "phone": "+7 (861) 890-66-77",
        "email": "v.romanova@rushimprom.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "документация",
        "issue_summary": "Сравнительная таблица характеристик: стандарт / Ex d / Ex ia",
        "original_text": "Просим предоставить сравнительную таблицу характеристик моделей ДГС-230 в исполнениях: стандарт, Ex d, Ex ia — по параметрам времени отклика, погрешности и диапазону рабочих температур.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 2, 26, 9, 50),
        "full_name": "Константинов Евгений Аркадьевич",
        "facility": "АО «ТюменьГазСтрой»",
        "phone": "+7 (3452) 901-77-88",
        "email": "e.konstantinov@tgs72.ru",
        "device_numbers": "ДГС-230/H2",
        "device_type": "газоанализатор",
        "emotional_tone": "Негатив",
        "category": "hardware",
        "issue_summary": "Шум ±0,4 мА на токовом выходе 4–20 мА",
        "original_text": "Сигнал 4–20 мА с датчика ДГС-230/H2 имеет выраженный шум около ±0,4 мА при нулевых показаниях. ПЛК Siemens фиксирует это как ненулевую концентрацию. Экранирование кабеля выполнено, расстояние до частотного преобразователя — 8 м.",
        "ai_response": None,
        "status": "В работе",
    },
    {
        "created_at": datetime(2026, 2, 27, 16, 45),
        "full_name": "Ильина Надежда Сергеевна",
        "facility": "ООО «ГазКонтрольСервис»",
        "phone": "+7 (495) 012-88-99",
        "email": "n.ilina@gkserv.ru",
        "device_numbers": "ДГС-230",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "software",
        "issue_summary": "Feature Request: централизованное OTA-обновление прошивки для 200 датчиков",
        "original_text": "Обслуживаем парк из 200 датчиков ЭРИС на нескольких объектах. Уточните, возможно ли централизованное онлайн-обновление прошивки через OTA. Ручное обновление каждого прибора занимает слишком много ресурсов. Если такого функционала нет — рассматривайте как Feature Request.",
        "ai_response": None,
        "status": "Новое",
    },
    {
        "created_at": datetime(2026, 2, 28, 11, 0),
        "full_name": "Сергеев Алексей Петрович",
        "facility": "ООО «НордГазМонтаж»",
        "phone": "+7 (81631) 1-23-45",
        "email": "a.sergeev@nordgazmontag.ru",
        "device_numbers": "ДГС-230/CH4",
        "device_type": "газоанализатор",
        "emotional_tone": "Нейтрально",
        "category": "hardware",
        "issue_summary": "Возможное ложное срабатывание до 23% НКПР на компрессорной станции",
        "original_text": "Газоанализатор ДГС-230/CH4 (зав. № 2502-01174) при подаче поверочного газа 50% НКПР выходит корректно. Однако при эксплуатации на компрессорной станции фиксирует до 23% НКПР без видимых источников утечки. Прошу помочь разобраться.",
        "ai_response": None,
        "status": "В работе",
    },
]


def seed_tickets() -> None:
    """Insert demo tickets if the table is empty."""
    with SessionLocal() as db:
        count = db.execute(select(func.count()).select_from(Ticket)).scalar_one()
        if count > 0:
            return  # already seeded

        for data in SEED_TICKETS:
            t = Ticket(**data)
            db.add(t)

        db.commit()
